# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.0
  - 1.5
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
jobs:
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.build(verbose=true);
                                    Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - travis_wait 30 julia --project=docs/ docs/make.jl
  allow_failures:
    - julia: nightly
after_success:
  - julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'
